{% set name = "reprit" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 601c1464d4337ce6053c33b9af5eb55b13a4581fcded3ebb95413ebbe143a2f7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5.3
    - pip
  run:
    - python >=3.5.3

test:
  imports:
    - reprit

about:
  home: https://github.com/lycantropos/reprit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Auto __repr__ method generation.
  description: Auto __repr__ method generation.
  doc_url: https://reprit.readthedocs.io/en/latest
  dev_url: https://github.com/lycantropos/reprit

extra:
  recipe-maintainers:
    - bretttully
    - lycantropos
